import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusPill } from "./IssueBadge";
import { RotateCcw, Eye, RefreshCw } from "lucide-react";
import { toast } from "sonner";

type Batch = {
  id: string;
  batch_name: string;
  generated_by: string | null;
  operator_id: string | null;
  source_mode: string;
  markets_total: number;
  markets_ready: number;
  markets_warned: number;
  markets_failed: number;
  markets_published: number;
  status: string;
  processing_ms: number | null;
  created_at: string;
};

type Props = { onView: (batchId: string) => void };

export const HistoryTab = ({ onView }: Props) => {
  const [batches, setBatches] = useState<Batch[]>([]);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("market_import_batches")
      .select("id,batch_name,generated_by,operator_id,source_mode,markets_total,markets_ready,markets_warned,markets_failed,markets_published,status,processing_ms,created_at")
      .order("created_at", { ascending: false })
      .limit(100);
    if (error) toast.error(error.message);
    setBatches((data as any) || []);
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  const rollback = async (id: string) => {
    if (!confirm("Rollback this batch? All markets published from it will be cancelled.")) return;
    const { data, error } = await supabase.functions.invoke("import-markets-rollback", { body: { batchId: id } });
    if (error || (data as any)?.error) { toast.error(error?.message || (data as any)?.error); return; }
    toast.success(`Rolled back ${(data as any)?.rolledBack ?? 0} markets`);
    load();
  };

  return (
    <Card className="p-3">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-semibold">Import history</h3>
        <Button size="sm" variant="outline" onClick={load} disabled={loading} className="gap-1.5">
          <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Refresh
        </Button>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="text-xs uppercase text-muted-foreground border-b border-border/40">
            <tr>
              <th className="text-left py-2 px-2">Batch</th>
              <th className="text-left py-2 px-2">Source</th>
              <th className="text-left py-2 px-2">Generated by</th>
              <th className="text-right py-2 px-2">Total</th>
              <th className="text-right py-2 px-2">Published</th>
              <th className="text-right py-2 px-2">Errors</th>
              <th className="text-left py-2 px-2">Status</th>
              <th className="text-left py-2 px-2">When</th>
              <th className="text-right py-2 px-2">Actions</th>
            </tr>
          </thead>
          <tbody>
            {batches.map((b) => (
              <tr key={b.id} className="border-b border-border/20">
                <td className="py-2 px-2 font-medium">{b.batch_name}</td>
                <td className="py-2 px-2 text-muted-foreground">{b.source_mode}</td>
                <td className="py-2 px-2 text-muted-foreground">{b.generated_by ?? "—"}</td>
                <td className="py-2 px-2 text-right">{b.markets_total}</td>
                <td className="py-2 px-2 text-right">{b.markets_published}</td>
                <td className="py-2 px-2 text-right">{b.markets_failed}</td>
                <td className="py-2 px-2"><StatusPill status={(b.status as any) ?? "ready"} /></td>
                <td className="py-2 px-2 text-muted-foreground text-xs">{new Date(b.created_at).toLocaleString()}</td>
                <td className="py-2 px-2 text-right">
                  <div className="inline-flex gap-1">
                    <Button size="sm" variant="ghost" onClick={() => onView(b.id)} className="h-7 px-2"><Eye className="h-3.5 w-3.5" /></Button>
                    {b.markets_published > 0 && b.status !== "rolled_back" && (
                      <Button size="sm" variant="ghost" onClick={() => rollback(b.id)} className="h-7 px-2 text-destructive"><RotateCcw className="h-3.5 w-3.5" /></Button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
            {!batches.length && !loading && (
              <tr><td colSpan={9} className="text-center text-muted-foreground py-8">No imports yet</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </Card>
  );
};
