import { SCHEMA_VERSION } from "./schema";

/**
 * Adapter layer: normalize arbitrary incoming market JSON shapes into the
 * canonical MarketPackage the Pagaza importer understands.
 *
 * Supported inputs:
 *  1. A full MarketPackage `{ version, batchName, generatedBy, markets: [...] }`
 *  2. A bare array `[{...}, {...}]` — auto-wrapped as an untitled batch
 *  3. Markets using compact keys: `title / closeTime / settlementSource /
 *     settlementRule / autoSettle / marketType` (as generated by the LDX
 *     master spec). Binary markets without `outcomes` get auto-injected
 *     YES/NO outcomes.
 */

const CATEGORY_MAP: Record<string, string> = {
  economy: "economy",
  economics: "economy",
  forex: "forex",
  crypto: "crypto",
  commodities: "commodities",
  weather: "weather",
  politics: "politics",
  sports: "sports",
  entertainment: "entertainment",
  technology: "technology",
};

function normalizeCategory(c: unknown): string | undefined {
  if (typeof c !== "string" || !c.trim()) return undefined;
  const key = c.trim().toLowerCase();
  return CATEGORY_MAP[key] ?? key;
}

function normalizeMarket(raw: any): any {
  if (!raw || typeof raw !== "object") return raw;
  const m: any = { ...raw };

  // Field aliases -> canonical
  if (m.title && !m.question) { m.question = m.title; delete m.title; }
  if (m.closeTime && !m.closesAt) { m.closesAt = m.closeTime; delete m.closeTime; }
  if (m.resolveTime && !m.resolvesAt) { m.resolvesAt = m.resolveTime; delete m.resolveTime; }
  if (m.settlementRule && !m.resolutionRules) { m.resolutionRules = m.settlementRule; delete m.settlementRule; }

  // marketType binary => YES/NO if outcomes missing
  if (!Array.isArray(m.outcomes) || m.outcomes.length === 0) {
    if (m.marketType === "binary" || m.marketType === "yes_no" || m.marketType === undefined) {
      m.outcomes = [{ label: "YES" }, { label: "NO" }];
      m.marketType = "binary";
    }
  }

  // settlementSource -> sources[]
  if (m.settlementSource && (!Array.isArray(m.sources) || m.sources.length === 0)) {
    m.sources = [{ publisher: String(m.settlementSource), sourceType: "official" }];
    delete m.settlementSource;
  }

  // Category normalization
  const cat = normalizeCategory(m.category);
  if (cat) m.category = cat;

  return m;
}

export function isMarketPackage(v: unknown): v is Record<string, unknown> {
  return !!v && typeof v === "object" && Array.isArray((v as any).markets);
}

/**
 * Take arbitrary user-supplied JSON, produce a canonical MarketPackage.
 * Does not validate — that's the validator's job. Only reshapes.
 */
export function normalizeIncoming(raw: unknown): unknown {
  if (Array.isArray(raw)) {
    return {
      version: SCHEMA_VERSION,
      batchName: `Untitled batch ${new Date().toISOString().slice(0, 16)}`,
      generatedBy: "manual",
      generatedAt: new Date().toISOString(),
      markets: raw.map(normalizeMarket),
    };
  }
  if (isMarketPackage(raw)) {
    const pkg = raw as any;
    return {
      ...pkg,
      version: pkg.version ?? SCHEMA_VERSION,
      markets: (pkg.markets as unknown[]).map(normalizeMarket),
    };
  }
  // Single market object — wrap
  if (raw && typeof raw === "object") {
    return {
      version: SCHEMA_VERSION,
      batchName: `Untitled batch ${new Date().toISOString().slice(0, 16)}`,
      generatedBy: "manual",
      generatedAt: new Date().toISOString(),
      markets: [normalizeMarket(raw)],
    };
  }
  return raw;
}
