// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwkpznrxtmhvgmmnyukc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3a3B6bnJ4dG1odmdtbW55dWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2OTkwNDQsImV4cCI6MjA4ODI3NTA0NH0._WtfCQ4w8SzkH3214OPZQHYgrez3FipdyA0y28L3W-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});